### ISSUE TITLE
attrs mod doesn't get block context 

### ISSUE THREAD

**Issue by Yeti-or** [bem/bem-xjst#421]
https://goo.gl/jHqyY4

In bemjson attrs values we could use other entities:
```
{ 
    block: 'button', 
    attrs: {
        // this works
        name: { block: 'button', elem: 'key'},
        // this doesn't
        id: { elem: 'key'}
    }
}
```
but elems don't behave as in other modes (content, mix)

**Comment by miripiruni** [comment]
Because in case  `id: { elem: 'key' }` BEMHTML takes `{elem: 'key' }` as an input bemjson and starts templating. 
1) https://github.com/bem/bem-xjst/blob/master/lib/bemhtml/index.js#L175
2) https://github.com/bem/bem-xjst/blob/master/lib/bemxjst/index.js#L314

If I’ll change this behaviour as you wish (extend `{elem: 'key'}` with `block` and `elem` from context) it may harm backward capability.

If you don’t mind I close this issue.
